const { assert } = require('chai');
const  { performance } = require('perf_hooks');
const commonChild  = require('../src/index');

describe('Test case 2',function(){

  it('1) common characters "HARRY", "SALLY" 2', function () {
    let start = performance.now()
    const result = commonChild("HARRY", "SALLY")
    let end = performance.now()
    t1 = end - start
    assert.equal(result, 2);
  });

  it('2)common characters "SHINCHAN", "NOHARAAA" 3', function () {
    let start = performance.now()
    const result = commonChild("SHINCHAN", "NOHARAAA")
    let end = performance.now()
    t2 = end - start;
    assert.equal(result, 3);
  });

  it('3) common characters "ABCDEF", "FBDAMN" 2', function () {
    let start = performance.now()
    const result = commonChild("ABCDEF", "FBDAMN")
    let end = performance.now()
    t3 = end - start;
    assert.equal(result, 2);
  });

  it('4) common characters "STACK", "TACKS" 4', function () {
    let start = performance.now()
    const result = commonChild("STACK", "TACKS")
    let end = performance.now()
    t4 = end - start;
    assert.equal(result, 4);
  });

  it('5) common characters "FDCBADGDGF", "GSGSFABCDR" 3', function () {
    let start = performance.now()
    const result = commonChild("FDCBADGDGF", "GSGSFABCDR")
    let end = performance.now()
    t5 = end - start;
    assert.equal(result, 3);
  });

  it('6) common characters "TJBSJKVBSKJNDBKDKNDBFNVDNBBNML", "TKJHGFGHJKLOIUYTDFVBNMJHGFDJCK" 10', function () {
    let start = performance.now()
    const result = commonChild("TJBSJKVBSKJNDBKDKNDBFNVDNBBNML", "TKJHGFGHJKLOIUYTDFVBNMJHGFDJCK")
    let end = performance.now()
    t6 = end - start;
    assert.equal(result, 10);
  });

  it('7) common characters should be 84', function () {
    let start = performance.now()
    const result = commonChild("HENTXADZCCZZZPOPESVYCROMUBJPDGBGUHBSMUQSYGEHUCRDACDYJIPYBLPXQUOLSELHBBBYQHKIOVFMSXAN" +
      "OMKMOXNPTGZSVHMCAEFSCNMCPHFUHOMNRNEQBOSLMAHJAMSMQMGKTLVKBVTSUDDWKXHHIIAFVNMQIHVVEPACCEVVECWOBVZVTWWMDIKYZAGZJOLQ" +
      "CINZZVZFNJGTCXXVLRAGJQFDMYMNKQDWNCLRTPYCCXEQFGKQWQSSYXNGELLNMAKNPIKFNKUIDCRUTWSTRKIHUAOGMPXO",
      "VNHLJXVVEXIPHEZZCKLKXNKLAYSHPSWWBPOQXZJYNFWBYVMMTMKFWJVPGHTGXCMBKTBWIXQJAMGVNRALOCACXIICCVEWKKSFDBMPRJUEYCHRO" +
      "EDXTKYJYSGVITYMVSAAEVKDAEDXWDBSHFTXDCDRTLCCFAKWSBNTPUSXIGTSXOVPIMVURDXOGBOOQAHISZBKADCRXVSJSICXWQNMQGCCPTHWHKFKD" +
      "XUGARNLREDXZIROXZTXPAVOGORNCVXGAMFVJUKLGPHSZKVVMRMFXLYUZNDUYOIIHJCK")
    let end = performance.now()
    t7 = end - start;
    assert.equal(result, 84);
  });

  it('8) common characters should be 143', function () {
    let start = performance.now()
    const result = commonChild("TYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTT" +
      "RTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJ" +
      "DHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTRTYTFGJDHMYJJRVKVBJDKKIHTTR",
      "TJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJ" +
      "KJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGU" +
      "KQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOGTJJDFYJKJHGHGUKQWVBJDKHPOG")
    let end = performance.now()
    t8 = end - start;
    assert.equal(result, 143);
  });

  it('9) common characters should be 1003', function () {
    let start = performance.now()
    const result = commonChild("BLCRCQQMXZCBACBDSFGIQDKFFHGPOGSZLHLXNZSSXRGVKIGNABASNFZDHVJOAINPZEZNDWOWSEJGMOVPPXHB" +
      "ERDJXLJSPAQDKNQEJMTBMVTPRXOCHYPKMDGRIHUPBQWZBNIXJBPTFYRMIUNXLVKPIRLLGJVGBIBIGDRIWGKEIKKYGCCFHCTEVNJPWFCFPDOXQDYG" +
      "HRRNXTFQRGCTITBUEPHPEIXQMYSKLYQXZWVRWDBYLJRBOWRAHRWUJWZKEGBCEHVTKJERFIJVWWVSRVNIDHYVEYIWAPHYSIKCBDBDWXAWXEHRFMHC" +
      "QNHTBYOFYJBIKFGJGUDIMQKNFCKMWNGVROISVLPZZCRUKHBWPSHRBSERBQOJXFTKSDDCRBIACQMHIOQBNESXTNURRXONVMNGZBMBDZDBWGXMFNCJ" +
      "WVUICKVQHUDDMVHNHRAHRDHOITKDDRRMFSQFZSLAASQSKJTVWTOSWQSPEARPEWADMMNSPCZTMKGVQOBGOBMGICUZNBEBZBFDRPFJPLCJOUTZBNJA" +
      "KTTMQPQVQOGVHIBNWFXOQWSMUSCBBCZURZOYRHSTKIFUXWROLBQBLYEDXQHKXYZNWVDCRAABKUBAPCPLKPZRQWNSWRCLNGDYLICBQAPPFNIDNCRM" +
      "ZEJJNNSUDDMAAOJPDQZPBRYKMVACVMTNNPQZBWHYALBHLDAYTJGJOWXQYVQQVNHLJXVVEXIPHEZZCKLKXNKLAYSHPSWWBPOQXZJYNFWBYVMMTMKF" +
      "WJVPGHTGXCMBKTBWIXQJAMGVNRALOCACXIICCVEWKKSFDBMPRJUEYCHROEDXTKYJYSGVITYMVSAAEVKDAEDXWDBSHFTXDCDRTLCCFAKWSBNTPUSX" +
      "IGTSXOVPIMVURDXOGBOOQAHISZBKADCRXVSJSICXWQNMQGCCPTHWHKFKDXUGARNLREDXZIROXZTXPAVOGORNCVXGAMFVJUKLGPHSZKVVMRMFXLYU" +
      "ZNDUYOIIHJCKDWQXNCIYNGFLZNGFTIHZHJSQGQQYICYKYAPAFJMYXIRFHFISJZJAVHMQLPBFXSPEEQAUJIIVSVLCRVHSMIGXQIVOOAFHIQOAOJBO" +
      "TGJUPXEPQZFJSNLVDHCXMDRPPGTUNBIMARYQXUTMQVGOVZDYSCBCHRTTAYEIFFNAGFDFGEFJNAXKWUYNFPETFYTHRLEICJEFDFHJFADZFBRABLMD" +
      "YNGIBXHGWDOWIFLWUKFVFUIITQGFRCGUYFZINJYIGXCKNPVDPMUKTVOIBSIUUDQDWXTJAIGVSFROIGSEOWNZAWDRIZFLFQAYQKETDOYLUOHSVUYO" +
      "JLDCJNIWFGDOFBRLWXQSCCTDEQHGHUXCHTCFSZRTRESSXNVOXFAHSWUAVJXMHCKRCOYVENGGBSXXYPEPUAQFNNCRVFQQDFCBPNTTNISDVORWBJBB" +
      "CVVNLYUTTSBPRXSKYFEKOMIZCGNSQHZYVCHHILQLGCLIKTNCLQUOUAXFNHJPIZYBYWSVMGUVAGXANTEZHSDUDBVVCAGCPKJAQXIOQOCTNNOOFUYZ" +
      "EGGPAEQGRRDREZUSVTKCQAZQDZAEIIGOCJPMQXRHRFQTCBNEMSAPSSLHXJVDBCSGQVUPGNCZKTFEBRIKWKSYXWRAHGNGYLLXFKJOUNXKDRWMBVOZ" +
      "GEOBAYYNFDNHHWFVPOKWUFLZTZUCMLGFVUWFXSVYYUBGRHAUWHBQSNIHENTXADZCCZZZPOPESVYCROMUBJPDGBGUHBSMUQSYGEHUCRDACDYJIPYB" +
      "LPXQUOLSELHBBBYQHKIOVFMSXANOMKMOXNPTGZSVHMCAEFSCNMCPHFUHOMNRNEQBOSLMAHJAMSMQMGKTLVKBVTSUDDWKXHHIIAFVNMQIHVVEPACC" +
      "EVVECWOBVZVTWWMDIKYZAGZJOLQCINZZVZFNJGTCXXVLRAGJQFDMYMNKQDWNCLRTPYCCXEQFGKQWQSSYXNGELLNMAKNPIKFNKUIDCRUTWSTRKIHU" +
      "AOGMPXOBQTFFAQMKGF",
      "LZNGFTIHZHJSQGQQYICYKYAPAFJMYXIRFHFISJZJAVHMQLPBFXSPEEQAUJIIVSVLCRVHSMIGXQIVOOAFHIQOAOJBOTGJUPXEPQZFJSNLVDHCX" +
      "MDRPPGTUNBIMARYQXUTMQVGOVZDYSCBCHRTTAYEIFFNAGFDFGEFJNAXKWUYNFPETFYTHRLEICJEFDFHJFADZFBRABLMDYNGIBXHGWDOWIFLWUKFV" +
      "FUIITQGFRCGUYFZINJYIGXCKNPVDPMUKTVOIBSIUUDQDWXTJAIGVSFROIGSEOWNZAWDRIZFLFQAYQKETDOYLUOHSVUYOJLDCJNIWFGDOFBRLWXQS" +
      "CCTDEQHGHUXCHTCFSZRTRESSXNVOXFAHSWUAVJXMHCKRCOYVENGGBSXXYPEPUAQFNNCRVFQQDFCBPNTTNISDVORWBJBBCVVNLYUTTSBPRXSKYFEK" +
      "OMIZCGNSQHZYVCHHILQLGCLIKTNCLQUOUAXFNHJPIZYBYWSVMGUVAGXANTEZHSDUDBVVCAGCPKJAQXIOQOCTNNOOFUYZEGGPAEQGRRDREZUSVTKC" +
      "QAZQDZAEIIGOCJPMQXRHRFQTCBNEMSAPSSLHXJVDBCSGQVUPGNCZKTFEBRIKWKSYXWRAHGNGYLLXFKJOUNXKDRWMBVOZGEOBAYYNFDNHHWFVPOKW" +
      "UFLZTZUCMLGFVUWFXSVYYUBGRHAUWHBQSNIHENTXADZCCZZZPOPESVYCROMUBJPDGBGUHBSMUQSYGEHUCRDACDYJIPYBLPXQUOLSELHBBBYQHKIO" +
      "VFMSXANOMKMOXNPTGZSVHMCAEFSCNMCPHFUHOMNRNEQBOSLMAHJAMSMQMGKTLVKBVTSUDDWKXHHIIAFVNMQIHVVEPACCEVVECWOBVZVTWWMDIKYZ" +
      "AGZJOLQCINZZVZFNJGTCXXVLRAGJQFDMYMNKQDWNCLRTPYCCXEQFGKQWQSSYXNGELLNMAKNPIKFNKUIDCRUTWSTRKIHUAOGMPXOBQTFFAQMKGFBL" +
      "CRCQQMXZCBACBDSFGIQDKFFHGPOGSZLHLXNZSSXRGVKIGNABASNFZDHVJOAINPZEZNDWOWSEJGMOVPPXHBERDJXLJSPAQDKNQEJMTBMVTPRXOCHY" +
      "PKMDGRIHUPBQWZBNIXJBPTFYRMIUNXLVKPIRLLGJVGBIBIGDRIWGKEIKKYGCCFHCTEVNJPWFCFPDOXQDYGHRRNXTFQRGCTITBUEPHPEIXQMYSKLY" +
      "QXZWVRWDBYLJRBOWRAHRWUJWZKEGBCEHVTKJERFIJVWWVSRVNIDHYVEYIWAPHYSIKCBDBDWXAWXEHRFMHCQNHTBYOFYJBIKFGJGUDIMQKNFCKMWN" +
      "GVROISVLPZZCRUKHBWPSHRBSERBQOJXFTKSDDCRBIACQMHIOQBNESXTNURRXONVMNGZBMBDZDBWGXMFNCJWVUICKVQHUDDMVHNHRAHRDHOITKDDR" +
      "RMFSQFZSLAASQSKJTVWTOSWQSPEARPEWADMMNSPCZTMKGVQOBGOBMGICUZNBEBZBFDRPFJPLCJOUTZBNJAKTTMQPQVQOGVHIBNWFXOQWSMUSCBBC" +
      "ZURZOYRHSTKIFUXWROLBQBLYEDXQHKXYZNWVDCRAABKUBAPCPLKPZRQWNSWRCLNGDYLICBQAPPFNIDNCRMZEJJNNSUDDMAAOJPDQZPBRYKMVACVM" +
      "TNNPQZBWHYALBHLDAYTJGJOWXQYVQQVNHLJXVVEXIPHEZZCKLKXNKLAYSHPSWWBPOQXZJYNFWBYVMMTMKFWJVPGHTGXCMBKTBWIXQJAMGVNRALOC" +
      "ACXIICCVEWKKSFDBMPRJUEYCHROEDXTKYJYSGVITYMVSAAEVKDAEDXWDBSHFTXDCDRTLCCFAKWSBNTPUSXIGTSXOVPIMVURDXOGBOOQAHISZBKAD" +
      "CRXVSJSICXWQNMQGCCPTHWHKFKDXUGARNLREDXZIROXZTXPAVOGORNCVXGAMFVJUKLGPHSZKVVMRMFXLYUZNDUYOIIHJCKDWQXNCIYNGF")
    let end = performance.now()
    t9 = end - start;
    assert.equal(result, 1003);
  });

  after(function() {
    let sumTime1 = t1 + t2 + t3 + t4 + t5 + t6 + t7 + t8 + t9
    console.log('Test case 2 = ' + sumTime1)
  });
});
